### ISSUE TITLE
Use web crypto API when possible

### ISSUE THREAD

**Issue by feross** [michaelrhodes/simple-sha1#2]
The web crypto API should be faster than any JS implementation (in theory). I haven't tested this yet.

In order to support it though, we'll need to change the API to take a callback (since the web crypto API uses promises). Is this a change you're willing to accept here? If not, I can publish this as a new module.

**Comment by michaelrhodes** [comment]
Definitely open to this. Maybe rather than doing away with the synchronous API (I quite like the simplicity), we could just move it to `require('simple-sha1/sync')`? Then `index.js` could become something like:

``` js
var sha1 = require('./sync')

module.exports = function (buf, raw, cb) {
  if (typeof raw === 'function') {
    cb = raw, raw = undefined
  }
  cb(null, sha1(buf, raw))
}
```

**Comment by feross** [comment]
Looks like we get more than a 2x speedup for using the web crypto API in the browser.

I'm looking at the use case of dropping a 250MB file on https://instant.io which splits it up into pieces (roughly 250KB) and hashes each piece to create a .torrent file.

before (with PR #1): 2167.267ms
after (with web crypto): 948.419ms

These measurements include other stuff that `create-torrent` is doing, so the speedup to `simple-sha1` is likely greater than 2-3x.

**Comment by feross** [comment]
I'll send a PR. I'll keep the sync functionality.

But I'm concerned that the polymorphic function (making `raw` optional) will cause de-optimizations in V8. Are you attached to the raw functionality?

**Comment by michaelrhodes** [comment]
Wow, that’s great!
I’m not attached to `raw` at all, so feel free to dump it.

**Comment by feross** [comment]
PR out: https://github.com/michaelrhodes/simple-sha1/pull/3

**Comment by michaelrhodes** [comment]
Are you able to send me your benchmark code? It’d be good to ensure that future changes don’t adversely affect performance.

**Comment by michaelrhodes** [comment]
Maybe in gist form?

**Comment by feross** [comment]
This is the code that I was timing: https://github.com/feross/create-torrent/blob/master/index.js#L169-L187

Essentially, we just need to make a lot of buffers and sha1 them all in parallel. When it's all done, we end the timer. There's some perf testing boilerplate we could steal from https://github.com/feross/buffer/blob/master/perf/copy.js and apply here.

**Comment by michaelrhodes** [comment]
Okay sweet, I’ll try to take a look into that tonight. :)

**Comment by michaelrhodes** [comment]
I’ve just added a [really basic benchmark](https://github.com/michaelrhodes/simple-sha1/blob/master/benchmark.js) that hashes a single buffer. I'm content with that, but I’ve made you a collaborator, so you can change it to meet your needs.
