### ISSUE TITLE
Automatic node and browser testing

### ISSUE THREAD

**Issue by feross** [michaelrhodes/simple-sha1#4]
Want me to send a PR that adds automatic travis and sauce labs testing so we can test that this works in lots of different browser versions? Would make me more confident that it works correctly. Plus, we'll get a badge like on https://github.com/feross/buffer!

**Comment by michaelrhodes** [comment]
Haha yeah, sure. I was just being lazy because it's such a minimal wrapper.

**Comment by feross** [comment]
Yeah, I know what you mean :) But now with the web crypto stuff in here, it's a little trickier :)

**Comment by feross** [comment]
About to send a PR adding sauce labs testing via zuul.

**Comment by feross** [comment]
PR out: #5

**Comment by michaelrhodes** [comment]
Thanks for setting that up, it was going to take me a bit to work out the sauce labs workflow. I miss testling. :'(

**Comment by feross** [comment]
Me too!
